#include "common.h"
#include "exact-merge.h"

// load data from rcpp_exact_initial into the EXMerge struct. The gr data are
// pre-sorted by increasing d.
void exact_merge::exmerge_init (const Rcpp::DataFrame &gr,
        exact_merge::EXMerge &cldat)
{
    Rcpp::IntegerVector from = gr ["from"];
    Rcpp::IntegerVector to = gr ["to"];
    Rcpp::NumericVector d = gr ["d"];
    Rcpp::IntegerVector clnum = gr ["cl"];
    Rcpp::IntegerVector clfrom = gr ["cl_from"];
    Rcpp::IntegerVector clto = gr ["cl_to"];

    const size_t n = static_cast <size_t> (d.size ());
    
    cldat.edges.resize (n);
    int2intset_map_t cl2edge_map;
    // The EXMerge struct has a set of inter-cluster edges which are filled
    // here; the rest of the struct is filled below
    for (int i = 0; i < n; i++)
    {
        if (clnum [i] >= 0) // edge in a cluster
        {
            int clnum_i = clnum [i];
            intset_t edgeset;
            if (cl2edge_map.find (clnum_i) != cl2edge_map.end ())
                edgeset = cl2edge_map.at (clnum_i);
            edgeset.emplace (static_cast <int> (i));
            cl2edge_map [clnum_i] = edgeset;
        } else // fill inter-cluster edge
        {
            utils::OneEdge edgei;
            // from and to hold cluster numbers, NOT vertex numbers
            edgei.from = clfrom [i];
            edgei.to = clto [i];
            edgei.dist = d [i];
            cldat.edges [static_cast <size_t> (i)] = edgei;
        }
    }

    // Fill intra-cluster data:
    const size_t ncl = cl2edge_map.size ();
    cldat.clusters.resize (ncl);
    for (int i = 0; i < ncl; i++)
    {
        OneCluster cli;
        intset_t edgeset = cl2edge_map.at (i);
        cli.id = static_cast <int> (i);
        cli.n = static_cast <int> (edgeset.size ());
        cli.dist_sum = 0.0;
        cli.dist_max = 0.0;
        for (auto ei: edgeset)
        {
            cli.dist_sum += ei;
            if (ei > cli.dist_max)
                cli.dist_max = ei;
        }
        cldat.clusters [static_cast <size_t> (i)] = cli;

        cldat.cl2index_map.emplace (i, i);
    }
}

// merge cluster clfrom with clto; clto remains as it was but is no longer
// indexed so simply ignored from that point on
exact_merge::OneMerge exact_merge::exmerge_merge (exact_merge::EXMerge &cldat,
        int clfrom_i, int clto_i, index_t ei)
{
    index_t cl_from_i_idx = cldat.cl2index_map.at (clfrom_i),
            cl_to_i_idx = cldat.cl2index_map.at (clto_i);
    exact_merge::OneCluster clfrom = cldat.clusters [cl_from_i_idx],
               clto = cldat.clusters [cl_to_i_idx];
    clto.n += clfrom.n;
    clto.dist_sum += clfrom.dist_sum;
    if (clfrom.dist_max > clto.dist_max)
        clto.dist_max = clfrom.dist_max;

    std::vector <utils::OneEdge> edges_from = clfrom.edges, edges_to = clto.edges;
    edges_to.insert (edges_to.end (), edges_from.begin (), edges_from.end ());
    clto.edges.clear ();
    clto.edges.shrink_to_fit ();
    clto.edges = edges_to;

    cldat.cl2index_map.at (clfrom_i) = cldat.cl2index_map.at (clto_i);

    exact_merge::OneMerge the_merge;
    the_merge.cli = clfrom_i;
    the_merge.clj = clto_i;
    the_merge.merge_dist = cldat.edges [ei].dist;

    return the_merge;
}

void exact_merge::exmerge_single (exact_merge::EXMerge &cldat)
{
    std::unordered_set <std::string> merges;
    index_t edgei = 0;
    while (cldat.clusters.size () > 1)
    {
        std::string merge_pr = std::to_string (cldat.edges [edgei].from) + "-" +
                               std::to_string (cldat.edges [edgei].to);
        if (merges.find (merge_pr) == merges.end ())
        {
            OneMerge the_merge = exmerge_merge (cldat,
                    cldat.edges [edgei].from,
                    cldat.edges [edgei].to,
                    edgei);
        }
        edgei++;
        if (edgei == cldat.edges.size ())
            break;
    }
}

void exact_merge::exmerge_avg (exact_merge::EXMerge &cldat)
{
}

void exact_merge::exmerge_max (exact_merge::EXMerge &cldat)
{
}



//' rcpp_exact_merge
//'
//' Merge clusters generated by rcpp_exact_initial to obtain specified number of
//' clusters.
//'
//' @noRd
// [[Rcpp::export]]
Rcpp::IntegerVector rcpp_exact_merge (
        const Rcpp::DataFrame gr,
        const int ncl,
        const std::string method)
{
    exact_merge::EXMerge clmerge_dat;
    exact_merge::exmerge_init (gr, clmerge_dat);

    if (utils::strfound (method, "single"))
    {
        exact_merge::exmerge_single (clmerge_dat);
    } else if (utils::strfound (method, "average"))
    {
        exact_merge::exmerge_avg (clmerge_dat);
    } else if (utils::strfound (method, "max"))
    {
        exact_merge::exmerge_max (clmerge_dat);
    } else
        Rcpp::stop ("method not found for exact_merge");

    Rcpp::IntegerVector res;
    return res;
}
