#include "common.h"
#include "exact-merge.h"

//' rcpp_exact_merge
//'
//' Merge clusters generated by rcpp_exact_initial to obtain specified number of
//' clusters.
//'
//' @noRd
// [[Rcpp::export]]
Rcpp::IntegerVector rcpp_exact_merge (
        const Rcpp::DataFrame gr,
        const int ncl,
        const std::string method)
{
    EXMerge clmerge_dat;
    if (strfound (method, "single")) // strfound from utils.cpp
    {
    } else if (strfound (method, "average"))
    {
    } else if (strfound (method, "max"))
    {
    } else
        Rcpp::stop ("method not found for rcpp_exact_merge");

    Rcpp::IntegerVector res;
    return res;
}
