#pragma once

#include "utils.h"

// --------- EXACT MERGE ----------------
//
// Merge the clusters generated by the rcpp_exact_initial

struct OneCluster
{
    int id, n;
    std::unordered_set <int> edge_id;
    double dist_sum, dist_max;
};

struct EXMerge
{
    std::vector <OneCluster> clusters;
    std::unordered_map <int, int> clfrom2indx_map, clto2index_map;
    std::vector <OneEdge> edges; // edges between clusters
};

Rcpp::IntegerVector rcpp_exact_merge (
        const Rcpp::DataFrame gr,
        const int ncl,
        const std::string method);
