#pragma once

#include "utils.h"

// --------- EXACT MERGE ----------------
//
// Merge the clusters generated by the rcpp_exact_initial. Seperate class and
// routines to allow results from rcpp_exact_initial to be returned and cached
// for subsequent re-merging.

struct OneCluster
{
    int id, n;
    double dist_sum, dist_max;
    std::vector <OneEdge> edges;
};

struct EXMerge
{
    std::vector <OneCluster> clusters;
    //std::unordered_map <int, int> clfrom2indx_map, clto2index_map;
    std::vector <OneEdge> edges; // edges between clusters
};

void rcpp_exmerge_init (EXMerge &cldat);
void rcpp_exmerge_single (EXMerge &cldat);
void rcpp_exmerge_avg (EXMerge &cldat);
void rcpp_exmerge_max (EXMerge &cldat);

Rcpp::IntegerVector rcpp_exact_merge (
        const Rcpp::DataFrame gr,
        const int ncl,
        const std::string method);
