#pragma once

#include <deque>

#include "utils.h"

// Merge the clusters generated by the rcpp_full_initial. Separate class and
// routines to allow results from rcpp_full_initial to be returned and cached
// for subsequent re-merging.

namespace full_merge {

struct OneCluster
{
    int id;
    size_t n;
    double dist_sum, dist_max;
    std::vector <utils::OneEdge> edges;
};

struct OneMerge
{
    int cli, clj;
    double merge_dist;
};

struct FullMergeDat
{
    bool shortest;
    std::unordered_map <int, int> cl_remap;
    std::unordered_map <int, intset_t> cl_members;
    std::unordered_map <int, OneCluster> clusters;
    std::vector <utils::OneEdge> edges; // edges between clusters
    std::vector <OneMerge> merges;
};

struct OneDist
{
    int cli, clj;
    size_t ni, nj;
    double di, dj, d, value; 
    // di, dj are dist_sums, d is min dist of connecting edge
};

struct AvgDists
{
    std::unordered_map <int, indxset_t> cl_map;
    std::deque <OneDist> avg_dists;
};

void init (const Rcpp::DataFrame &gr, FullMergeDat &cldat);

OneMerge merge_one_single (FullMergeDat &cldat, index_t ei);
void merge_single (FullMergeDat &cldat);

bool avgdist_sorter_incr (const OneDist &lhs, const OneDist &rhs);
bool avgdist_sorter_decr (const OneDist &lhs, const OneDist &rhs);
void fill_avg_dists (FullMergeDat &cldat, AvgDists &cl_dists);
void fill_cl_indx_maps (AvgDists &cl_dists);
OneMerge merge_avg (FullMergeDat &cldat, AvgDists &cl_dists);
void avg (FullMergeDat &cldat);

bool maxdist_sorter_incr (const OneDist &lhs, const OneDist &rhs);
bool maxdist_sorter_decr (const OneDist &lhs, const OneDist &rhs);
void fill_max_dists (FullMergeDat &cldat, AvgDists &cl_dists);
OneMerge merge_max (FullMergeDat &cldat, AvgDists &cl_dists);
void max (FullMergeDat &cldat);

} // end namespace full_merge

Rcpp::NumericMatrix rcpp_full_merge (
        const Rcpp::DataFrame gr,
        const std::string method,
        const bool shortest);
