// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpp_alk
Rcpp::IntegerVector rcpp_alk(const Rcpp::DataFrame gr);
RcppExport SEXP _spatialcluster_rcpp_alk(SEXP grSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr(grSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_alk(gr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_clk
Rcpp::IntegerVector rcpp_clk(const Rcpp::DataFrame gr_full, const Rcpp::DataFrame gr);
RcppExport SEXP _spatialcluster_rcpp_clk(SEXP gr_fullSEXP, SEXP grSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr_full(gr_fullSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr(grSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_clk(gr_full, gr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_cut_tree
Rcpp::IntegerVector rcpp_cut_tree(const Rcpp::DataFrame tree, const int ncl, const bool distances);
RcppExport SEXP _spatialcluster_rcpp_cut_tree(SEXP treeSEXP, SEXP nclSEXP, SEXP distancesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type tree(treeSEXP);
    Rcpp::traits::input_parameter< const int >::type ncl(nclSEXP);
    Rcpp::traits::input_parameter< const bool >::type distances(distancesSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_cut_tree(tree, ncl, distances));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_exact_initial
Rcpp::IntegerVector rcpp_exact_initial(const Rcpp::DataFrame gr);
RcppExport SEXP _spatialcluster_rcpp_exact_initial(SEXP grSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr(grSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_exact_initial(gr));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_exact_merge
Rcpp::NumericMatrix rcpp_exact_merge(const Rcpp::DataFrame gr, const std::string linkage);
RcppExport SEXP _spatialcluster_rcpp_exact_merge(SEXP grSEXP, SEXP linkageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr(grSEXP);
    Rcpp::traits::input_parameter< const std::string >::type linkage(linkageSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_exact_merge(gr, linkage));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_slk
Rcpp::IntegerVector rcpp_slk(const Rcpp::DataFrame gr_full, const Rcpp::DataFrame gr);
RcppExport SEXP _spatialcluster_rcpp_slk(SEXP gr_fullSEXP, SEXP grSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr_full(gr_fullSEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame >::type gr(grSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_slk(gr_full, gr));
    return rcpp_result_gen;
END_RCPP
}
