# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_alk
#'
#' Full-order average linkage cluster redcap algorithm
#'
#' @noRd
rcpp_alk <- function(gr) {
    .Call(`_spatialcluster_rcpp_alk`, gr)
}

#' clk_step
#'
#' @param ei The i'th edge of the full sorted list of edge weights
#' @noRd
NULL

#' rcpp_clk
#'
#' Full-order complete linkage cluster redcap algorithm
#'
#' @noRd
rcpp_clk <- function(gr_full, gr) {
    .Call(`_spatialcluster_rcpp_clk`, gr_full, gr)
}

#' rcpp_cut_tree
#'
#' Cut tree into specified number of clusters by minimising internal cluster
#' variance.
#'
#' @param tree tree to be processed
#'
#' @return Vector of cluster IDs for each tree edge
#' @noRd
rcpp_cut_tree <- function(tree, ncl) {
    .Call(`_spatialcluster_rcpp_cut_tree`, tree, ncl)
}

#' step
#'
#' All edges are initially in their own clusters. This merges edge#i with the
#' next closest edge
#'
#' @param ei The i'th edge of the sorted list of NN edge weights
#' @noRd
NULL

#' fill_cl_edges
#'
#' Fill (arma) matrix of strongest/shortest connections between all clusters
#' used to construct the hierarchical relationships
#' @noRd
NULL

#' rcpp_exact_initial
#'
#' Initial allocation for exact clustering
#'
#' @noRd
rcpp_exact_initial <- function(gr) {
    .Call(`_spatialcluster_rcpp_exact_initial`, gr)
}

#' rcpp_exact_merge
#'
#' Merge clusters generated by rcpp_exact_initial to full hierarchy of all
#' possible merges.
#'
#' @noRd
rcpp_exact_merge <- function(gr, linkage) {
    .Call(`_spatialcluster_rcpp_exact_merge`, gr, linkage)
}

#' rcpp_slk
#'
#' Full-order single linkage cluster redcap algorithm
#'
#' @noRd
rcpp_slk <- function(gr_full, gr) {
    .Call(`_spatialcluster_rcpp_slk`, gr_full, gr)
}

